export enum BatchProgressStatus {
    TRANSLATION = "TRANSLATION",
    REVIEW = "REVIEW",
    EXPERT_REVIEW = "EXPERT_REVIEW",
    AUDIO_RECORDING = "AUDIO_RECORDING",
    AUDIO_REVIEWING = "AUDIO_REVIEWING",
    AUDIO_EXPERT_REVIEWING = "AUDIO_EXPERT_REVIEWING",
}
