export enum UserBatchRole {

    TEXT_TRANSLATOR="TEXT_TRANSLATOR",
    AUDIO_TRANSCRIBER="AUDIO_TRANSCRIBER",
    TEXT_VERIFIER="TEXT_VERIFIER",
    AUDIO_RECORDER = "AUDIO_RECORDER",
    AUDIO_VERIFIER="AUDIO_VERIFIER",
    EXPERT_TEXT_REVIEWER ="EXPERT_TEXT_REVIEWER",
    EXPERT_AUDIO_REVIEWER = "EXPERT_AUDIO_REVIEWER"

}